<?php

/**
 * Evaluate characteristics of a module.
 *
 * @param string $module_name
 *  The name of the module to evaluate.
 *
 * @return boolean
 *  true if the module passed all checks.
 *
 */
function ah_ready_module_check($module_name) {

  $result = true;

  $failed[] = module_exists($module_name);

  if (in_array(true, $failed)) {
    $result = false;
  }

  return $result;
}

/**
 * Implements hook_acquia_spi_test().
 *
 * @see acquia_connector/acquia_spi/acquia_spi.api.php for more information.
 *
 */
function ah_ready_acquia_spi_test() {

  return array(
    'adaptive_image_enabled_check' => array(
      'description'    => 'Adaptive Image causes all visitors to see the image as it was rendered for the device associated with the first page load after a cache clear.',
      'solved_message' => 'Adaptive Image module is disabled',
      'failed_message' => 'Adaptive Image module is enabled',
      'solved'         => ah_ready_module_check('adaptive_image'),
      'fix_details'    => 'Disable the Adaptive Image module and re-architect responsive images to work with Varnish caching.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'apc_enabled_check' => array(
      'description'    => 'Alternative PHP Cache stores data per-server, and use of the APC module can lead to divergence in cache data.',
      'solved_message' => 'APC module is disabled',
      'failed_message' => 'APC module is enabled',
      'solved'         => ah_ready_module_check('apc'),
      'fix_details'    => 'Disable the APC module so that Acquia\'s Opcode Cache can perform to it\'s fullest.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'boost_enabled_check' => array(
      'description'    => 'Boost creates many disk writes, which can cause problems on shared servers. On Acquia Hosting, it is also superceded by Varnish. For more details see our documentation: https://docs.acquia.com/articles/boost-acquia-cloud',
      'solved_message' => 'Boost module is disabled',
      'failed_message' => 'Boost module is enabled',
      'solved'         => ah_ready_module_check('boost'),
      'fix_details'    => 'Disable the Boost module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'cas_enabled_check' => array(
      'description'    => 'CAS requires session cookies to be set, which prevents Varnish from caching pages.',
      'solved_message' => 'CAS is disabled',
      'failed_message' => 'CAS is enabled',
      'solved'         => ah_ready_module_check('cas'),
      'fix_details'    => 'Disable the CAS module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'contact_importer_enabled_check' => array(
      'description'    => 'Contact Importer is dependent on Open Inviter. To use this module, it is strongly recommended to create a symlink to private files. For more information see: https://docs.acquia.com/cloud/files',
      'solved_message' => 'Contact Importer is disabled',
      'failed_message' => 'Contact Importer is enabled',
      'solved'         => ah_ready_module_check('contact_importer'),
      'fix_details'    => 'Disable Contact Importer or ensure proper configuration.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'db_maintenance_enabled_check' => array(
      'description'    => 'Using this module improperly can potentially cause slowdowns or outages. If you feel your site has tables that need optimizing, open a ticket with support.',
      'solved_message' => 'DB Maintenance is disabled',
      'failed_message' => 'DB Maintenance is enabled',
      'solved'         => ah_ready_module_check('db_maintenance'),
      'fix_details'    => 'Disable DB Maintenance or open a support ticket for optimization assistance.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'elysia_cron_enabled_check' => array(
      'description'    => 'Elysia Cron is not incompatible, but requires careful setup. Poor implementations of this module can cause severe performance problems. For more details see: https://docs.acquia.com/articles/elysia-cron-acquia-cloud',
      'solved_message' => 'Elysia Cron is disabled',
      'failed_message' => 'Elysia Cron is enabled',
      'solved'         => ah_ready_module_check('elysia_cron'),
      'fix_details'    => 'Ensure that Elysia Cron is configured properly.',
      'category'       => 'performance',
      'severity'       => 16,
    ),
    'fbconnect_enabled_check' => array(
      'description'    => 'Facebook Connect requires session cookies to be set,, which prevents Varnish from caching pages.',
      'solved_message' => 'Facebook Connect is disabled',
      'failed_message' => 'Facebook Connect is enabled',
      'solved'         => ah_ready_module_check('fbconnect'),
      'fix_details'    => 'Disable the Facebook Connect module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'filecache_enabled_check' => array(
      'description'    => 'File Cache moves caching to Gluster, which can cause server load to spike in association with file system activity.',
      'solved_message' => 'File Cache is disabled',
      'failed_message' => 'File Cache is enabled',
      'solved'         => ah_ready_module_check('filecache'),
      'fix_details'    => 'Disable the File Cache module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    // @TODO: This should be a check for File Conveyor mode in the CDN module.
    // 'fileconveyor_enabled_check' => array(
    //   'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
    //   'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
    //   'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
    //   'solved'         => ah_ready_module_check('fileconveyor'),
    //   'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
    //   'category'       => 'performance',
    //   'severity'       => 32,
    // ),
    'fivestar_enabled_check' => array(
      'description'    => 'When used with Anonymous user voting, this module can create significant amounts of data in the cache_form table.',
      'solved_message' => 'Fivestar is disabled',
      'failed_message' => 'Fivestar is enabled',
      'solved'         => ah_ready_module_check('fivestar'),
      'fix_details'    => 'Disable or patch the Fivestar module (https://drupal.org/node/1512568), or disallow Anonymous users the ability to vote.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'hierarchical_select_enabled_check' => array(
      'description'    => 'Hierarchical Select requires session cookies to be set, which prevents Varnish from caching pages.',
      'solved_message' => 'Hierarchical Select is disabled',
      'failed_message' => 'Hierarchical Select is enabled',
      'solved'         => ah_ready_module_check('hierarchical_select'),
      'fix_details'    => 'Disable the Hierarchical Select module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'htmlpurifier_enabled_check' => array(
      'description'    => 'HTML Purifier should be configured with a symlink to private files.',
      'solved_message' => 'HTML Purifier is disabled',
      'failed_message' => 'HTML Purifier is enabled',
      'solved'         => ah_ready_module_check('htmlpurifier'),
      'fix_details'    => 'Configure HTML Purifier to utilize private files via symlink.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'imagefield_crop_enabled_check' => array(
      'description'    => 'Imagefield Crop adds lots of data to the Variables table, and can cause problems with memory consumption.',
      'solved_message' => 'Imagefield Crop is disabled',
      'failed_message' => 'Imagefield Crop is enabled',
      'solved'         => ah_ready_module_check('imagefield_crop'),
      'fix_details'    => 'Disable the Imagefield Crop module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'ip_geoloc_enabled_check' => array(
      'description'    => 'IP Geolocation Views and Maps requires session cookies to be set, which prevents Varnish from caching pages.',
      'solved_message' => 'IP Geolocation Views and Maps is disabled',
      'failed_message' => 'IP Geolocation Views and Maps is enabled',
      'solved'         => ah_ready_module_check('ip_geoloc'),
      'fix_details'    => 'Disable the IP Geolocation Views and Maps module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'ldap_enabled_check' => array(
      'description'    => 'LDAP alone without SSO can work on Acquia Cloud. SSO requires NTLM (NT LAN Manager) support, which is an Apache module that Acquia does not currently support.',
      'solved_message' => 'LDAP is disabled',
      'failed_message' => 'LDAP is enabled',
      'solved'         => ah_ready_module_check('ldap'),
      'fix_details'    => 'Disable the LDAP module or disable LDAP SSO.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'linkchecker_enabled_check' => array(
      'description'    => 'Link Checker can cause timeouts during cron runs.',
      'solved_message' => 'Link Checker is disabled',
      'failed_message' => 'Link Checker is enabled',
      'solved'         => ah_ready_module_check('linkchecker'),
      'fix_details'    => 'Disable the Link Checker module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'pubdlcnt_enabled_check' => array(
      'description'    => 'Public Download Count prevents Varnish from caching pages. Google Analytics is a good replacement option.',
      'solved_message' => 'Public Download Count is disabled',
      'failed_message' => 'Public Download Count is enabled',
      'solved'         => ah_ready_module_check('pubdlcnt'),
      'fix_details'    => 'Disable the Public Download Count module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'purge_enabled_check' => array(
      'description'    => 'Purge (7.x-1.x) is not specifically incompatible, but can be difficult to set up correctly. We suggest using Acquia Purge instead. It is specifically intended for use on Acquia Cloud. Over time, these modules are planned to merge.',
      'solved_message' => 'Purge is disabled',
      'failed_message' => 'Purge is enabled',
      'solved'         => ah_ready_module_check('purge'),
      'fix_details'    => 'Disable the Purge module in favor of Acquia Purge.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'quicktabs_enabled_check' => array(
      'description'    => 'Quick Tabs loads content that a user does not immediately see, and creates additional links. This causes crawlers to visit pages 2-n times, which can impact site responsiveness.',
      'solved_message' => 'Quick Tabs is disabled',
      'failed_message' => 'Quick Tabs is enabled',
      'solved'         => ah_ready_module_check('quicktabs'),
      'fix_details'    => 'Disable the Quick Tabs module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'recaptcha_enabled_check' => array(
      'description'    => 'reCAPTCHA requires session cookies to be set, which prevents Varnish from caching pages.',
      'solved_message' => 'reCAPTCHA is disabled',
      'failed_message' => 'reCAPTCHA is enabled',
      'solved'         => ah_ready_module_check('recaptcha'),
      'fix_details'    => 'Disable the reCAPTCHA module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'role_memory_limit_enabled_check' => array(
      'description'    => 'Role Memory Limit overrides memory limit tuning, putting servers at risk of memory exhaustion. For more information see: https://docs.acquia.com/cloud/configure/environments/php#php-mem',
      'solved_message' => 'Role Memory Limit is disabled',
      'failed_message' => 'Role Memory Limit is enabled',
      'solved'         => ah_ready_module_check('role_memory_limit'),
      'fix_details'    => 'Disable the Role Memory Limit module. Open a Support ticket to learn options for setting safe memory limits.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'search404_enabled_check' => array(
      'description'    => 'Search 404 triggers a search for 404 Not Found responses. This module is best used with Fast 404 to prevent triggering a search for missing media assets.',
      'solved_message' => 'Search 404 is disabled',
      'failed_message' => 'Search 404 is enabled',
      'solved'         => ah_ready_module_check('search404'),
      'fix_details'    => 'Disable the Search 404 module or configure with Fast 404.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'session_api_enabled_check' => array(
      'description'    => 'Session API requires session cookies to be set, which prevents Varnish from caching pages. Additionally, Session API generates intense queries, causing major slowdowns.',
      'solved_message' => 'Session API is disabled',
      'failed_message' => 'Session API is enabled',
      'solved'         => ah_ready_module_check('session_api'),
      'fix_details'    => 'Disable the Session API module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    // @TODO: This should be a check for both search_api and apachesolr
    // 'search_api_solr_enabled_check' => array(
    //   'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
    //   'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
    //   'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
    //   'solved'         => ah_ready_module_check('search_api_solr'),
    //   'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
    //   'category'       => 'performance',
    //   'severity'       => 32,
    // ),
    // @TODO: Find current info for Shibboleth support.
    // 'shib_auth_enabled_check' => array(
    //   'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
    //   'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
    //   'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
    //   'solved'         => ah_ready_module_check('shib_auth'),
    //   'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
    //   'category'       => 'performance',
    //   'severity'       => 32,
    // ),
    'simplesamlphp_auth_enabled_check' => array(
      'description'    => 'Installing simpleSAMLphp Authentication on Acquia Cloud requires special care. For more information see: https://docs.acquia.com/articles/using-simplesamlphp-acquia-cloud-site',
      'solved_message' => 'simpleSAMLphp Authentication is disabled',
      'failed_message' => 'simpleSAMLphp Authentication is enabled',
      'solved'         => ah_ready_module_check('simplesamlphp_auth'),
      'fix_details'    => 'Follow Acquia\'s documentation to properly install and configure simpleSAMLphp Authentication. For more information see: https://docs.acquia.com/articles/using-simplesamlphp-acquia-cloud-site',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'tcpdf_enabled_check' => array(
      'description'    => 'TCPDF should be configured with a symlink to private files.',
      'solved_message' => 'TCPDF is disabled',
      'failed_message' => 'TCPDF is enabled',
      'solved'         => ah_ready_module_check('tcpdf'),
      'fix_details'    => 'Disable the TCPDF module or ensure proper configuration on Acquia Cloud.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'textsize_enabled_check' => array(
      'description'    => 'Text Size requires session cookies to be set, which prevents Varnish from caching pages.',
      'solved_message' => 'Text Size is disabled',
      'failed_message' => 'Text Size is enabled',
      'solved'         => ah_ready_module_check('textsize'),
      'fix_details'    => 'Disable the Text Size module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'varnish_enabled_check' => array(
      'description'    => 'The Varnish contributed module does not work with Acquia Cloud because it requires connections to the load balancers, which Acquia does not provide. The Varnish caching provided by Acquia Cloud works out of the box with Pressflow (Drupal 6) or Drupal 7 sites with caching enabled.',
      'solved_message' => 'Varnish is disabled',
      'failed_message' => 'Varnish is enabled',
      'solved'         => ah_ready_module_check('varnish'),
      'fix_details'    => 'Disable the Varnish module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    // @TODO: This should check for workbench_moderation, apachesolr, and apachesolr_workbench_moderation
    'workbench_moderation_enabled_check' => array(
      'description'    => 'Workbench Moderation does not work out of the box with ApacheSolr search integration. For more information see: https://docs.acquia.com/articles/workbench-moderation-can-cause-problems-apachesolr',
      'solved_message' => 'Workbench Moderation is disabled',
      'failed_message' => 'Workbench Moderation is enabled',
      'solved'         => ah_ready_module_check('workbench_moderation'),
      'fix_details'    => 'To use Workbench Moderation with ApacheSolr search integration, ensure the ApacheSolr Workbench Moderation module is installed.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'wurfl_enabled_check' => array(
      'description'    => 'WURFL should be configured with a symlink to private files.',
      'solved_message' => 'WURFL is disabled',
      'failed_message' => 'WURFL is enabled',
      'solved'         => ah_ready_module_check('wurfl'),
      'fix_details'    => 'Disable the WURFL module or ensure proper configuration on Acquia Cloud.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    'WYSIWYG-CKFinder_enabled_check' => array(
      'description'    => 'WYSIWYG CKFinder should be configured with a symlink to private files.',
      'solved_message' => 'WYSIWYG CKFinder is disabled',
      'failed_message' => 'WYSIWYG CKFinder is enabled',
      'solved'         => ah_ready_module_check('WYSIWYG-CKFinder'),
      'fix_details'    => 'Disable the WYSIWYG CKFinder module or ensure proper configuration on Acquia Cloud.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
    // @TODO: Add check for plupload_temporary_uri variable
    'plupload_enabled_check' => array(
      'description'    => 'Plupload can fail on high availability server architecture. For a solution see: https://docs.acquia.com/articles/correcting-broken-uploads-plupload-acquia-cloud-enterprise',
      'solved_message' => 'Plupload is disabled',
      'failed_message' => 'Plupload is enabled',
      'solved'         => ah_ready_module_check('plupload'),
      'fix_details'    => 'Ensure Plupload is configured for Acquia Cloud Enterprise. For a solution see: https://docs.acquia.com/articles/correcting-broken-uploads-plupload-acquia-cloud-enterprise',
      'category'       => 'performance',
      'severity'       => 16,
    ),
  );
}
