<?php

/**
 * Evaluate characteristics of a module.
 *
 * @param string $module_name
 *  The name of the module to evaluate.
 *
 * @return boolean
 *  true if the module passed all checks.
 *
 */
function ah_ready_module_check($module_name) {

  $result = true;

  $failed[] = module_exists($module_name);

  if (in_array(true, $failed)) {
    $result = false;
  }

  return $result;
}

/**
 * Implements hook_acquia_spi_test().
 *
 * @see acquia_connector/acquia_spi/acquia_spi.api.php for more information.
 *
 */
function ah_ready_acquia_spi_test() {

  return array(
    'boost_enabled_check' => array(
      'description'    => 'Boost creates many disk writes, which can cause problems on shared servers.',
      'solved_message' => 'Boost module is disabled',
      'failed_message' => 'Boost module is enabled',
      'solved'         => ah_ready_module_check('boost'),
      'fix_details'    => 'Disable the Boost module.',
      'category'       => 'performance',
      'severity'       => 32,
    ),
//    'cas_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('cas'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'contact_importer_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('contact_importer'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'context_show_regions_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('context_show_regions'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'db_maintenance_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('db_maintenance'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'ds_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('ds'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'elysia_cron_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('elysia_cron'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'fbconnect_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('fbconnect'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'fileconveyor_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('fileconveyor'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'fivestar_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('fivestar'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'hierarchical_select_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('hierarchical_select'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'htmlpurifier_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('htmlpurifier'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'imagefield_crop_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('imagefield_crop'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'lightbox2_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('lightbox2'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'linkchecker_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('linkchecker'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'multicron_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('multicron'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'oauth_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('oauth'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'pubdlcnt_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('pubdlcnt'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'purge_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('purge'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'quicktabs_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('quicktabs'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'recaptcha_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('recaptcha'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'search404_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('search404'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'session_api_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('session_api'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'shib_auth_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('shib_auth'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'simplesamlphp_auth_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('simplesamlphp_auth'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'supercron_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('supercron'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'textsize_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('textsize'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'varnish_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('varnish'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'wurfl_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('wurfl'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
//    'plupload_enabled_check' => array(
//      'description'    => 'The Acquia SPI module automates the collection of site information. It is required for use with the Acquia Insight service.',
//      'solved_message' => 'Huzzah! The Acquia SPI module is enabled',
//      'failed_message' => 'Ruh-Roh! The Acquia SPI module is not enabled',
//      'solved'         => ah_ready_module_check('plupload'),
//      'fix_details'    => 'Enable or download the Acquia agent module. This can be downloaded via Drush or from Drupal.org.',
//      'category'       => 'performance',
//      'severity'       => 32,
//    ),
  );
}
